### PR TITLE
Added better handling for challenge response requests

### LINKED ISSUE #13: Authentication failed.
Utilizing the develop branch commit a53cb082b6a07f32ddc5c9cacff6f5dfe926f170

Using this code which seems to be entirely correct doesn't seem to authenticate correctly
```
    config = ce.get_config('Cognito', args.configfile)
    u = Cognito(config['pool_id'],config['client_id'], username=args.username)
    response = u.authenticate(args.password)

```

```
2017-04-11 12:24:16 DEBUG parsers.parse Response body:
{"ChallengeName":"NEW_PASSWORD_REQUIRED","ChallengeParameters":{"requiredAttributes":"[]","userAttributes":"{\"email_verified\":\"true\",\"email\":\"<ommitted email>\"}"},"Session":"<sessiong string ommitted>"}
2017-04-11 12:24:16 DEBUG hooks._emit Event needs-retry.cognito-idp.RespondToAuthChallenge: calling handler <botocore.retryhandler.RetryHandler object at 0x7fc01d531d90>
2017-04-11 12:24:16 DEBUG retryhandler.__call__ No retry needed.
Traceback (most recent call last):
  File "bin/auth-cognito", line 37, in <module>
    main()
  File "bin/auth-cognito", line 33, in main
    response = u.authenticate(args.password)
  File "~/.local/lib/python2.7/site-packages/warrant/__init__.py", line 213, in authenticate
    self.id_token = tokens['AuthenticationResult']['IdToken']
KeyError: 'AuthenticationResult'
```

It doesn't look like there is support for Challenges of NEW_PASSWORD_REQUIRED and it failed to raise like it should https://github.com/capless/warrant/blob/develop/warrant/aws_srp.py#L187

### PR DESCRIPTION
**Pull request by blade2005**
Also I thought including some logging lines for easier to debugging.
Closes #13

### CODE REVIEW

**Comment by ebpetway** [comment]
Thanks for the pull request!

We're just about to release the current master branch to pypi, so I think we'll hold off on any updates to it until afterwards. I did look this over and here's my thoughts:

I don't think we'll be able to use the combination of the while loop and getpass to set the new password, since that pins us down to a very specific way of gathering the new password. Also, does the challenge response to `NEW_PASSWORD_REQUIRED` work without a session argument?

I started on some ideas on this yesterday, let me know what you think:
If the response `ChallengeName` is `NEW_PASSWORD_REQUIRED`, then we can set an attribute on the 
`AWSSRP` object, such as `new_password_requred = True`.
Then the user of the object, after trying the `authenticate` method, is responsible for checking that attribute, and then calling a `complete_new_password_challenge` method on the object after obtaining a new password from the end user.

**Comment by blade2005** [comment]
The handling isn't perfect for NEW_PASSWORD_REQUIRED I'd like there to be a module global which is a callable and returns back the password. Allows users to specify a system to get the password rather than using a TTY is present. That way the user can set their own handler
```
import warrant
import functools
warrant.GET_PASSWORD_METHOD = functools.partial(getpass.getpass, 'Password: ')
warrant.Cognito
.... rest of code.
```

And in the source it just checks that the global GET_PASSWORD_METHOD is a callable and calls it.

We could make use of a return from authenticate if the challenge is NEW_PASSWORD_REQUIRED and leave it entirely up to the user. 

I'm not sure if session is required. I reset my password in a different iteration of my code before doing the hacky while loop. But I think I did have to provide Session to it in order to make it work. So might need additional changes. 

I assume complete_new_password_challenge would like something like this

```
def complete_new_password_challenge(self, new_pw):
    data = {'USERNAME': self.username, 'NEW_PASSWORD': new_pw}
    response = boto_client.respond_to_auth_challenge()
```

In mine the user designs their own function that returns a password when it's needed. 

I think yours leaves more to the user than I would like. I like the idea of the library handling it yet still leaving the user the ability to set up their own method. 

On the other hand how would my method work for projects like django. Where you'd put in the password and then you'd know you need to ask the end-user for a new password.

**Comment by blade2005** [comment]
@ebpetway what are your thoughts on adding a bool return to authenticate?

I think could also be helpful in following with your idea for returning False if we failed to authenticate for any reason and then they check if AWSRP.new_password_requred then Cognito.complete_new_password_challenge

It also allows for simpler logic to say 
```
if u.authenticate(args.password):
    # continue
```

**Comment by blade2005** [comment]
Sorry for so many comments. 
I did some research about Session being required.
I created a new user as an admin and tried updating with the password and it failed due to missing session
```
botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the RespondToAuthChallenge operation: Missing required parameter Session
```

This indicates the current PR most definitely won't work and a more robust solution will need to be developed.

**Pull request closed without merging**
