### PR TITLE
Add admin_create_user method

### PR DESCRIPTION
**Pull request by grantmcconnaughey**

### CODE REVIEW

**Comment by bjinwright** [comment]
Are your PRs based off that first PR #20? If so I think that is why they are all failing.

**Comment by grantmcconnaughey** [comment]
Nope, they all branch off of master.

**Comment by grantmcconnaughey** [comment]
I can try to remove the changes to the trailing whitespace if you'd like. I've tried several different editors and they all remove trailing whitespace by default. I have to open the file in TextEdit so that they don't get removed. 😛

**Comment by bjinwright** [comment]
I figured out the problem. Travis won't use the environment variables for PRs if they are encrypted.

**Pull request merged**
